
P_TSCODE = {"ts_code": "股票代码（如 600519.SH / 000858.SZ）"}
P_TRADE_DATE = {"trade_date": "交易日期（YYYYMMDD）"}
P_START_END = {
    "start_date": "开始日期 (YYYYMMDD)",
    "end_date": "结束日期 (YYYYMMDD)",
}
P_LIMIT_OFFSET = {
    "limit": "单次返回条数上限",
    "offset": "偏移量（与 limit 配合翻页）",
}

def _a(category, sub, api, name, params=None, note=None):
    d = {"category": category, "sub": sub, "api": api, "name": name,
         "params": params or {}}
    if note:
        d["note"] = note
    return d

CATALOG = [
    _a("股票数据", "基础数据", "stock_basic", "股票列表",
       params={"ts_code": "股票代码（可选）", "name": "股票名称（可选）",
               "exchange": "交易所 SSE/SZSE/BSE（空=全部）",
               "market": "市场 主板/创业板/科创板/CDR（可选）",
               "list_status": "上市状态 L上市/D退市/P暂停上市，默认L",
               **P_LIMIT_OFFSET}),
    _a("股票数据", "基础数据", "trade_cal", "交易日历",
       params={"exchange": "交易所 SSE/SZSE/CFFEX/DCE/SHFE/CZCE/INE/GFEX",
               "start_date": P_START_END["start_date"],
               "end_date": P_START_END["end_date"],
               "is_open": "是否交易 0休市/1交易"}),
    _a("股票数据", "基础数据", "stock_company", "上市公司基本信息",
       params={"exchange": "交易所（可选）", "ts_code": P_TSCODE["ts_code"]}),
    _a("股票数据", "基础数据", "namechange", "股票曾用名",
       params={"ts_code": P_TSCODE["ts_code"], **P_START_END}),
    _a("股票数据", "基础数据", "stock_st", "ST股票列表",
       params={"ts_code": P_TSCODE["ts_code"], "type_": "ST类型（S/ST/*ST等）",
               **P_LIMIT_OFFSET}),
    _a("股票数据", "基础数据", "st", "ST风险警示板股票", note="同义接口，用于风险警示名单"),
    _a("股票数据", "基础数据", "stock_hsgt", "沪深港通股票列表",
       params={"hs_type": "SH-SZ沪股通/SH-HK沪港股通/SZ-SZ深股通/SZ-HK深港股通",
               "is_new": "最新记录 1是/0否（默认1）"}),
    _a("股票数据", "基础数据", "stk_premarket", "每日股本（盘前）",
       params={"ts_code": P_TSCODE["ts_code"], "trade_date": P_TRADE_DATE["trade_date"]}),
    _a("股票数据", "基础数据", "stk_managers", "上市公司管理层",
       params={"ts_code": P_TSCODE["ts_code"], **P_LIMIT_OFFSET}),
    _a("股票数据", "基础数据", "stk_rewards", "管理层薪酬和持股",
       params={"ts_code": P_TSCODE["ts_code"], "end_date": "报告期(YYYYMMDD)"},),
    _a("股票数据", "基础数据", "bse_mapping", "北交所新旧代码对照", params={}),
    _a("股票数据", "基础数据", "new_share", "IPO新股上市",
       params={**P_LIMIT_OFFSET, "start_date": "上网开始日期", "end_date": "上网结束日期"}),

    _a("股票数据", "行情数据", "daily", "历史日线",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END, **P_LIMIT_OFFSET},
       note="未复权日线 OHLCV+成交额；DATAHUB 实测稳定"),
    _a("股票数据", "行情数据", "weekly", "周线行情", params={**P_TSCODE, **P_START_END}),
    _a("股票数据", "行情数据", "monthly", "月线行情", params={**P_TSCODE, **P_START_END}),
    _a("股票数据", "行情数据", "stk_mins", "历史分钟",
       params={**P_TSCODE, "freq": "min/1min/5min/15min/30min/60min",
               **P_START_END}),
    _a("股票数据", "行情数据", "adj_factor", "复权因子",
       params={**P_TSCODE, "trade_date": P_TRADE_DATE["trade_date"], **P_START_END}),
    _a("股票数据", "行情数据", "pro_bar", "通用/复权行情",
       params={**P_TSCODE, "adj": "复权方式 qfq前/hfq后/None不复权",
               "freq": "D/W/M 或 min 系列", **P_START_END},
       note="⚠️ proxy 中转带 adj 易 500/回退 daily；DATAHUB 下走 daily 语义"),
    _a("股票数据", "行情数据", "daily_basic", "每日指标",
       params={**P_TSCODE, "trade_date": P_TRADE_DATE["trade_date"],
               **P_START_END, **P_LIMIT_OFFSET},
       note="PE/PB/PS/股息率/换手率/量比/总市值/流通市值等估值核心"),
    _a("股票数据", "行情数据", "bak_daily", "备用行情",
       params={**P_TSCODE, "trade_date": P_TRADE_DATE["trade_date"], **P_START_END}),
    _a("股票数据", "行情数据", "stk_limit", "每日涨跌停价格",
       params={**P_TSCODE, "trade_date": P_TRADE_DATE["trade_date"]}),
    _a("股票数据", "行情数据", "suspend_d", "每日停复牌信息",
       params={**P_TSCODE, "suspend_type": "S停牌/R复牌", **P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "行情数据", "hsgt_top10", "沪深股通十大成交股",
       params={"ts_code": P_TSCODE["ts_code"], **P_TRADE_DATE,
               "market_type": "市场类型", **P_LIMIT_OFFSET}),
    _a("股票数据", "行情数据", "rt_k", "实时日线", params={**P_TSCODE},
       note="实时接口，当日动态"),
    _a("股票数据", "行情数据", "rt_min", "实时分钟", params={**P_TSCODE}),
    _a("股票数据", "行情数据", "rt_min_daily", "A股实时分钟-日累计", params={**P_TSCODE}),
    _a("股票数据", "行情数据", "rt_etf_min", "ETF实时分钟", params={"ts_code": "ETF代码"}),
    _a("股票数据", "行情数据", "rt_etf_min_daily", "ETF实时分钟-日累计", params={"ts_code": "ETF代码"}),
    _a("股票数据", "行情数据", "rt_etf_k", "ETF实时日线", params={"ts_code": "ETF代码"}),

    _a("股票数据", "财务数据", "income", "利润表",
       params={**P_TSCODE, "ann_date": "公告日期", "f_ann_date": "实际公告日期",
               "end_date": "报告期(YYYYMMDD)", "report_type": "报告类型 1合并报表等",
               **P_LIMIT_OFFSET},
       note="营收/归母净利/研发费用等；DATAHUB 无 n_income_attr_p_cut 扣非字段"),
    _a("股票数据", "财务数据", "balancesheet", "资产负债表",
       params={**P_TSCODE, **P_TRADE_DATE, "ann_date": "公告日期",
               "end_date": "报告期", "report_type": "报告类型", **P_LIMIT_OFFSET}),
    _a("股票数据", "财务数据", "cashflow", "现金流量表",
       params={**P_TSCODE, "ann_date": "公告日期", "end_date": "报告期",
               "report_type": "报告类型", **P_LIMIT_OFFSET},
       note="含 free_cashflow；资本支出双名 c_pay_acq_const_fiolta"),
    _a("股票数据", "财务数据", "express", "业绩快报",
       params={**P_TSCODE, "ann_date": "公告日期", "end_date": "报告期"}),
    _a("股票数据", "财务数据", "forecast", "业绩预告",
       params={**P_TSCODE, "ann_date": "公告日期", "end_date": "报告期",
               "type_": "预告类型 预增/预减/扭亏等"}),
    _a("股票数据", "财务数据", "dividend", "分红送股数据",
       params={**P_TSCODE, "ann_date": "公告日期", "record_date": "股权登记日",
               "ex_date": "除权除息日", "imp_ann_date": "实施公告日"},
       note="分红连续性判断核心；历年可用 limit 拉全量"),
    _a("股票数据", "财务数据", "fina_audit", "财务审计意见",
       params={**P_TSCODE, "end_date": "报告期", "ann_date": "公告日期"}),
    _a("股票数据", "财务数据", "fina_indicator", "财务指标数据",
       params={**P_TSCODE, "ann_date": "公告日期", "end_date": "报告期",
               **P_LIMIT_OFFSET},
       note="ROE/ROIC/毛利率/周转率/EPS 等 100+ 字段；DATAHUB 不支持 period 参数，多年份用 limit 拉全量本地过滤；扣非用 profit_dedt"),
    _a("股票数据", "财务数据", "fina_mainbz", "主营业务构成",
       params={**P_TSCODE, "type_": "构成类型 按行业/按产品/按地区",
               "end_date": "报告期"}),
    _a("股票数据", "财务数据", "disclosure_date", "财报披露日期表",
       params={**P_TSCODE, "end_date": "报告期"}),

    _a("股票数据", "参考数据", "top10_holders", "前十大股东",
       params={**P_TSCODE, "end_date": "报告期", "ann_date": "公告日期", **P_START_END}),
    _a("股票数据", "参考数据", "top10_floatholders", "前十大流通股东",
       params={**P_TSCODE, "end_date": "报告期", **P_START_END}),
    _a("股票数据", "参考数据", "pledge_stat", "股权质押统计数据",
       params={**P_TSCODE, **P_TRADE_DATE}),
    _a("股票数据", "参考数据", "pledge_detail", "股权质押明细数据",
       params={**P_TSCODE, **P_TRADE_DATE}),
    _a("股票数据", "参考数据", "share_float", "限售股解禁",
       params={**P_TSCODE, **P_START_END, "float_date": "解禁日期"}),
    _a("股票数据", "参考数据", "repurchase", "股票回购",
       params={**P_TSCODE, **P_START_END, "ann_date": "公告日期"}),
    _a("股票数据", "参考数据", "block_trade", "大宗交易",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "参考数据", "stk_holdernumber", "股东人数",
       params={**P_TSCODE, "enddate": "统计截止日期", "enddate_min/max": "区间筛选"}),
    _a("股票数据", "参考数据", "stk_holdertrade", "股东增减持",
       params={**P_TSCODE, **P_TRADE_DATE, "holder_type": "股东类型"}),
    _a("股票数据", "参考数据", "stk_shock", "个股异常波动", params={**P_TSCODE, **P_TRADE_DATE}),
    _a("股票数据", "参考数据", "stk_high_shock", "个股严重异常波动", params={**P_TSCODE, **P_TRADE_DATE}),
    _a("股票数据", "参考数据", "stk_alert", "交易所重点提示证券", params={}),

    _a("股票数据", "特色数据", "cyq_perf", "每日筹码及胜率",
       params={**P_TSCODE, "trade_date": P_TRADE_DATE["trade_date"], **P_START_END}),
    _a("股票数据", "特色数据", "cyq_chips", "每日筹码分布",
       params={**P_TSCODE, "trade_date": P_TRADE_DATE["trade_date"]}),
    _a("股票数据", "特色数据", "stk_factor", "股票技术面因子",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END},
       note="MACD/KDJ/RSI/BOLL 等技术因子现成数据"),
    _a("股票数据", "特色数据", "stk_factor_pro", "股票技术面因子(专业版)",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END},
       note="更全的技术因子集（VIP 权限概率高）"),
    _a("股票数据", "特色数据", "stk_auction_o", "股票开盘集合竞价数据", params={**P_TSCODE}),
    _a("股票数据", "特色数据", "stk_auction_c", "股票收盘集合竞价数据", params={**P_TSCODE}),
    _a("股票数据", "特色数据", "stk_auction", "开盘竞价成交（当日）", params={}),
    _a("股票数据", "特色数据", "stk_nineturn", "神奇九转指标",
       params={**P_TSCODE}, note="涉及分钟数据，每天21点更新"),
    _a("股票数据", "特色数据", "stk_surv", "机构调研数据",
       params={**P_TSCODE, **P_START_END}),
    _a("股票数据", "特色数据", "stk_ah_comparison", "AH股比价", params={"ts_code": P_TSCODE["ts_code"], "trade_date": P_TRADE_DATE["trade_date"]}),
    _a("股票数据", "特色数据", "report_rc", "券商盈利预测数据",
       params={**P_TSCODE, "end_date": "截止日期"}),
    _a("股票数据", "特色数据", "broker_recommend", "券商月度金股",
       params={"month": "月份 YYYYMM", **P_LIMIT_OFFSET}),

    _a("股票数据", "两融及转融通", "margin", "融资融券交易汇总",
       params={**P_TRADE_DATE, "exchange": "SSE/SZSE", **P_START_END}),
    _a("股票数据", "两融及转融通", "margin_detail", "融资融券交易明细",
       params={**P_TRADE_DATE, "ts_code": P_TSCODE["ts_code"], **P_START_END}),
    _a("股票数据", "两融及转融通", "margin_secs", "融资融券标的（盘前）",
       params={**P_TRADE_DATE, "ts_code": P_TSCODE["ts_code"]}),
    _a("股票数据", "两融及转融通", "slb_len", "转融资交易汇总", params={**P_TRADE_DATE, "exchange": "交易所"}),
    _a("股票数据", "两融及转融通", "slb_sec", "转融券交易汇总(停)", params={}),
    _a("股票数据", "两融及转融通", "slb_sec_detail", "转融券交易明细(停)", params={}),
    _a("股票数据", "两融及转融通", "slb_len_mm", "做市借券交易汇总(停)", params={}),

    _a("股票数据", "资金流向数据", "moneyflow", "个股资金流向",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END},
       note="主力净流入 net_mf_amount（DATAHUB 字段名，对应官方 net_mf_inflow 语义）"),
    _a("股票数据", "资金流向数据", "moneyflow_ths", "个股资金流向（THS）",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "资金流向数据", "moneyflow_cnt_ths", "板块资金流向（THS）",
       params={**P_TRADE_DATE, "ts_code": "板块代码"}),
    _a("股票数据", "资金流向数据", "moneyflow_dc", "个股资金流向（DC）",
       params={**P_TSCODE, **P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "资金流向数据", "moneyflow_mkt_dc", "大盘资金流向（DC）",
       params={**P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "资金流向数据", "moneyflow_ind_ths", "行业资金流向（THS）",
       params={**P_TRADE_DATE, "ts_code": "行业代码"}),
    _a("股票数据", "资金流向数据", "moneyflow_ind_dc", "板块资金流向（DC）",
       params={**P_TRADE_DATE, "ts_code": "板块代码"}),

    _a("股票数据", "打板专题数据", "top_list", "龙虎榜每日统计单",
       params={**P_TRADE_DATE, **P_START_END, "ts_code": P_TSCODE["ts_code"]}),
    _a("股票数据", "打板专题数据", "top_inst", "龙虎榜机构交易单",
       params={**P_TRADE_DATE, "ts_code": P_TSCODE["ts_code"]}),
    _a("股票数据", "打板专题数据", "limit_list_d", "涨跌停和炸板数据",
       params={**P_TRADE_DATE, "limit_type": "U涨停/D跌停/Z炸板", **P_START_END}),
    _a("股票数据", "打板专题数据", "limit_list_ths", "THS涨跌停榜单", params={**P_TRADE_DATE}),
    _a("股票数据", "打板专题数据", "limit_step", "涨停股票连板天梯", params={**P_TRADE_DATE}),
    _a("股票数据", "打板专题数据", "limit_cpt_list", "涨停最强板块统计", params={**P_TRADE_DATE}),
    _a("股票数据", "打板专题数据", "ths_index", "THS概念板块分类", params={**P_LIMIT_OFFSET}),
    _a("股票数据", "打板专题数据", "ths_member", "THS概念板块成分",
       params={"ts_code": "指数/板块代码", "con_code": "成分股代码"}),
    _a("股票数据", "打板专题数据", "ths_daily", "THS概念板块行情",
       params={"ts_code": "板块代码", **P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "打板专题数据", "ths_hot", "THS热榜", params={"market": "A股/HK/US", "hot_type": "榜单类型"}),
    _a("股票数据", "打板专题数据", "dc_index", "DC概念板块分类", params={}),
    _a("股票数据", "打板专题数据", "dc_member", "DC概念板块成分", params={"ts_code": "板块代码"}),
    _a("股票数据", "打板专题数据", "dc_daily", "DC概念板块行情",
       params={"ts_code": "板块代码", **P_TRADE_DATE, **P_START_END}),
    _a("股票数据", "打板专题数据", "dc_hot", "DC热榜", params={}),
    _a("股票数据", "打板专题数据", "dc_concept", "题材数据（DC）", params={}),
    _a("股票数据", "打板专题数据", "dc_concept_cons", "题材成分（DC）", params={}),
    _a("股票数据", "打板专题数据", "tdx_index", "TDX概念板块分类", params={}),
    _a("股票数据", "打板专题数据", "tdx_member", "TDX概念板块成分", params={"ts_code": "板块代码"}),
    _a("股票数据", "打板专题数据", "tdx_daily", "TDX概念板块行情", params={"ts_code": "板块代码", **P_TRADE_DATE}),
    _a("股票数据", "打板专题数据", "kpl_list", "榜单数据（KP）",
       params={**P_TRADE_DATE, "tag": "标签筛选"}),
    _a("股票数据", "打板专题数据", "kpl_concept_cons", "题材成分（KP）", params={}),
    _a("股票数据", "打板专题数据", "hm_list", "市场游资最全名录", params={}),
    _a("股票数据", "打板专题数据", "hm_detail", "游资交易每日明细", params={**P_TRADE_DATE}),

    _a("ETF专题", "ETF基本信息", "etf_basic", "ETF基本信息",
       params={"ts_code": "ETF代码", "fund_type": "基金类型", "status": "上市状态"}),
    _a("ETF专题", "ETF日线行情", "fund_daily", "ETF日线行情",
       params={"ts_code": "ETF代码", **P_TRADE_DATE, **P_START_END}),
    _a("ETF专题", "ETF历史分钟", "etf_mins", "ETF历史分钟",
       params={"ts_code": "ETF代码", "freq": "min/5min/15min/30min/60min",
               **P_START_END}),
    _a("ETF专题", "ETF复权因子", "fund_adj", "ETF复权因子",
       params={"ts_code": "ETF代码", **P_START_END}),
    _a("ETF专题", "ETF跟踪指数", "etf_index", "ETF跟踪指数", params={}),
    _a("ETF专题", "ETF份额规模", "etf_share_size", "ETF份额规模", params={"trade_date": P_TRADE_DATE["trade_date"]}),
    _a("ETF专题", "每日篮子组合(沪市PCF)", "etf_sh_cons", "每日篮子组合(沪市PCF)", params={}),
    _a("ETF专题", "每日篮子组合(深市PCF)", "etf_sz_cons", "每日篮子组合(深市PCF)", params={}),
    _a("ETF专题", "ETF实时参考", "rt_etf_sz_iopv", "ETF实时参考", params={}),
    _a("ETF专题", "指数公司公告", "idx_anns", "指数公司公告", params={}),

    _a("指数专题", "指数基本信息", "index_basic", "指数基本信息",
       params={"market": "交易所或服务商（SSE/SZSE/CSI/MSCI等）", "ts_code": "指数代码"}),
    _a("指数专题", "指数日线行情", "index_daily", "指数日线行情",
       params={"ts_code": "指数代码（如 000001.SH 上证指数）", **P_START_END}),
    _a("指数专题", "指数周线行情", "index_weekly", "指数周线行情", params={"ts_code": "指数代码", **P_START_END}),
    _a("指数专题", "指数月线行情", "index_monthly", "指数月线行情", params={"ts_code": "指数代码", **P_START_END}),
    _a("指数专题", "指数实时日线", "rt_idx_k", "指数实时日线", params={}),
    _a("指数专题", "指数实时分钟", "rt_idx_min", "指数实时分钟", params={}),
    _a("指数专题", "指数历史分钟", "idx_mins", "指数历史分钟", params={"ts_code": "指数代码", "freq": "min系列"}),
    _a("指数专题", "大盘指数每日指标", "index_dailybasic", "大盘指数每日指标",
       params={"ts_code": "指数代码", **P_TRADE_DATE, **P_START_END},
       note="大盘 PE/PB/成交额/换手率等（市值级估值分位可用）"),
    _a("指数专题", "指数成分和权重", "index_weight", "指数成分和权重",
       params={"index_code": "指数代码", "trade_date": P_TRADE_DATE["trade_date"], **P_START_END}),
    _a("指数专题", "申万行业分类", "index_classify", "申万行业分类",
       params={"level": "层级 L1/L2/L3", "src": "来源 SW2014/SW2021", **P_LIMIT_OFFSET}),
    _a("指数专题", "申万行业成分（分级）", "index_member_all", "申万行业成分（分级）",
       params={"l1_code": "一级代码", "l2_code": "二级代码", "l3_code": "三级代码", "is_active": "是否有效"}),
    _a("指数专题", "申万日线行情", "sw_daily", "申万日线行情",
       params={"ts_code": "申万行业指数代码", **P_TRADE_DATE, **P_START_END}),
    _a("指数专题", "申万实时行情", "rt_sw_k", "申万实时行情", params={}),
    _a("指数专题", "SW历史分钟", "sw_mins", "SW历史分钟", params={"ts_code": "指数代码", "freq": "min系列"}),
    _a("指数专题", "中信行业成分", "ci_index_member", "中信行业成分", params={}),
    _a("指数专题", "中信行业指数日行情", "ci_daily", "中信行业指数日行情",
       params={"ts_code": "行业指数代码", **P_START_END}),
    _a("指数专题", "国际主要指数", "index_global", "国际主要指数",
       params={"ts_code": "国际指数代码", **P_TRADE_DATE, **P_START_END}),
    _a("指数专题", "指数技术面因子(专业版)", "idx_factor_pro", "指数技术面因子(专业版)", params={"ts_code": "指数代码"}),
    _a("指数专题", "沪深市场每日交易统计", "daily_info", "沪深市场每日交易统计",
       params={**P_TRADE_DATE, **P_START_END, "ts_code": "市场代码（沪深）"}),
    _a("指数专题", "深圳市场每日交易情况", "sz_daily_info", "深圳市场每日交易情况",
       params={**P_TRADE_DATE, **P_START_END}),

    _a("公募基金", "基金列表", "fund_basic", "基金列表",
       params={"market": "E场内/O场外", "status": "上市状态 D/I/L", **P_LIMIT_OFFSET}),
    _a("公募基金", "基金管理人", "fund_company", "基金管理人",
       params={"code": "管理人代码", "standard": "规范", **P_LIMIT_OFFSET}),
    _a("公募基金", "基金经理", "fund_manager", "基金经理",
       params={"id": "基金经理ID", "ann_date": "公告日期", **P_LIMIT_OFFSET}),
    _a("公募基金", "基金规模", "fund_share", "基金规模",
       params={"ts_code": "基金代码", "trade_date": P_TRADE_DATE["trade_date"], **P_START_END}),
    _a("公募基金", "基金净值", "fund_nav", "基金净值",
       params={"ts_code": "基金代码", "nav_date": "净值日期", **P_START_END}),
    _a("公募基金", "基金业绩基准", "mkt_idx_bmk", "基金业绩基准", params={}),
    _a("公募基金", "基金分红", "fund_div", "基金分红",
       params={"ts_code": "基金代码", "ann_date": "公告日期", **P_LIMIT_OFFSET}),
    _a("公募基金", "基金持仓", "fund_portfolio", "基金持仓",
       params={"ts_code": "基金代码", "end_date": "报告期", **P_START_END}),
    _a("公募基金", "基金技术面因子(专业版)", "fund_factor_pro", "基金技术面因子(专业版)", params={"ts_code": "基金代码"}),

    _a("期货数据", "合约信息", "fut_basic", "合约信息",
       params={"exchange": "交易所 CFFEX/DCE/SHFE/CZCE/INE/GFEX",
               "fut_type": "合约类型 1普通/2主连/3连续/4主力/5临期",
               "status": "上市状态 L上市/D退市/U未上市"}),
    _a("期货数据", "期货交易日历", "fut_trade_cal", "期货交易日历",
       params={"exchange": "交易所", "start_date": "开始日期", "end_date": "结束日期"}),
    _a("期货数据", "日线行情", "fut_daily", "日线行情",
       params={"ts_code": "期货代码", **P_TRADE_DATE, **P_START_END, "exchange": "交易所"}),
    _a("期货数据", "期货周/月线行情(每日更新)", "fut_weekly_monthly", "期货周/月线行情(每日更新)",
       params={"ts_code": "期货代码", "freq": "W周/M月", **P_START_END}),
    _a("期货数据", "仓单日报", "fut_wsr", "仓单日报",
       params={**P_TRADE_DATE, "symbol": "品种代码", "exchange": "交易所"}),
    _a("期货数据", "历史分钟行情", "ft_mins", "历史分钟行情",
       params={"ts_code": "期货代码", "freq": "min系列", **P_START_END}),
    _a("期货数据", "每日结算参数", "fut_settle", "每日结算参数",
       params={"ts_code": "期货代码", **P_TRADE_DATE, **P_START_END, "exchange": "交易所"}),
    _a("期货数据", "南华期货指数日线行情", "fut_index_daily", "南华期货指数日线行情",
       params={"ts_code": "指数代码", **P_START_END}),
    _a("期货数据", "实时分钟行情", "rt_fut_min", "实时分钟行情", params={"ts_code": "期货代码"}),
    _a("期货数据", "期货主力与连续合约", "fut_mapping", "期货主力与连续合约",
       params={"ts_code": "主力/连续合约代码"}),
    _a("期货数据", "每日持仓排名", "fut_holding", "每日持仓排名",
       params={**P_TRADE_DATE, "symbol": "品种代码", "exchange": "交易所"}),
    _a("期货数据", "期货主要品种交易周报", "fut_weekly_detail", "期货主要品种交易周报",
       params={"week_y": "年份", "week_w": "周序号", "symbol": "品种"}),
    _a("期货数据", "期货合约涨跌停价格", "ft_limit", "期货合约涨跌停价格",
       params={**P_TRADE_DATE, "ts_code": "合约代码"}),

    _a("现货数据", "上海黄金基础信息", "sge_basic", "上海黄金基础信息", params={}),
    _a("现货数据", "上海黄金现货日行情", "sge_daily", "上海黄金现货日行情",
       params={"symbol": "合约代码", **P_TRADE_DATE, **P_START_END}),
    _a("外汇数据", "外汇基础信息（海外）", "fx_obasic", "外汇基础信息（海外）", params={}),
    _a("外汇数据", "外汇日线行情", "fx_daily", "外汇日线行情",
       params={"ts_code": "货币对（如 USDCNH.FXCC）", **P_TRADE_DATE, **P_START_END}),
    _a("期权数据", "期权合约信息", "opt_basic", "期权合约信息",
       params={"exchange": "交易所 SOE/SSE/DCE/CZCE/GFEX/CFFEX/INE",
               "opt_code": "期权代码", "call_put": "C认购/P认沽", "trade_date": "交易日期"}),
    _a("期权数据", "期权日线行情", "opt_daily", "期权日线行情",
       params={"ts_code": "期权代码", "trade_date": P_TRADE_DATE["trade_date"], **P_START_END}),
    _a("期权数据", "期权分钟行情", "opt_mins", "期权分钟行情",
       params={"ts_code": "期权代码", "freq": "min系列", **P_START_END}),

    _a("债券专题", "可转债基础信息", "cb_basic", "可转债基础信息",
       params={"bond_id": "债券代码", "ts_code": "正股代码", **P_LIMIT_OFFSET}),
    _a("债券专题", "可转债发行", "cb_issue", "可转债发行",
       params={"ts_code": "正股代码", "bond_id": "债券代码"}),
    _a("债券专题", "可转债赎回信息", "cb_call", "可转债赎回信息",
       params={"ts_code": "正股代码", "bond_id": "债券代码"}),
    _a("债券专题", "可转债票面利率", "cb_rate", "可转债票面利率",
       params={"ts_code": "债券代码", "bank_field": "银行相关"}),
    _a("债券专题", "可转债行情", "cb_daily", "可转债行情",
       params={**P_TRADE_DATE, "ts_code": "转债代码", **P_START_END}),
    _a("债券专题", "可转债技术面因子(专业版)", "cb_factor_pro", "可转债技术面因子(专业版)", params={}),
    _a("债券专题", "可转债十大持有人", "top10_cb_holders", "可转债十大持有人",
       params={"bond_id": "债券代码", "end_date": "报告期"}),
    _a("债券专题", "可转债转股结果", "cb_share", "可转债转股结果",
       params={"bond_id": "债券代码", "ts_code": "正股代码", **P_START_END}),
    _a("债券专题", "可转债转股价变动", "cb_price_chg", "可转债转股价变动",
       params={"bond_id": "债券代码", "start_date": "开始日期", "end_date": "结束日期"}),
    _a("债券专题", "可转债债券评级", "cb_rating", "可转债债券评级",
       params={"bond_id": "债券代码", "end_date": "报告期"}),
    _a("债券专题", "国债收益率曲线", "yc_cb", "国债收益率曲线",
       params={"curve_type": "曲线类型", "trade_date": "交易日期", **P_START_END}),
    _a("债券专题", "债券回购日行情", "repo_daily", "债券回购日行情",
       params={"ts_code": "回购代码", **P_TRADE_DATE, **P_START_END}),
    _a("债券专题", "大宗交易", "bond_blk", "大宗交易",
       params={**P_TRADE_DATE, "ts_code": "债券代码"}),
    _a("债券专题", "大宗交易明细", "bond_blk_detail", "大宗交易明细",
       params={**P_TRADE_DATE, "ts_code": "债券代码"}),
    _a("债券专题", "柜台流通式债券报价", "bc_otcqt", "柜台流通式债券报价",
       params={"ts_code": "债券代码", **P_TRADE_DATE}),
    _a("债券专题", "柜台流通式债券最优报价", "bc_bestotcqt", "柜台流通式债券最优报价",
       params={"ts_code": "债券代码", **P_TRADE_DATE}),
    _a("债券专题", "全球财经事件", "eco_cal", "全球财经事件",
       params={**P_START_END, "currency": "币种", "country": "国家" }),

    _a("美股数据", "美股基础信息", "us_basic", "美股基础信息",
       params={"us_code": "美股代码（如 AAPL.US）", "rating": "评级", **P_LIMIT_OFFSET}),
    _a("美股数据", "美股交易日历", "us_tradecal", "美股交易日历",
       params={"exchange": "US全美/NASDAQ/NYSE/AMEX", **P_START_END, "is_open": "是否交易"}),
    _a("美股数据", "美股日线行情", "us_daily", "美股日线行情",
       params={"ts_code": "美股代码", **P_TRADE_DATE, **P_START_END}),
    _a("美股数据", "美股复权行情", "us_daily_adj", "美股复权行情",
       params={"ts_code": "美股代码", **P_START_END}),
    _a("美股数据", "美股复权因子", "us_adjfactor", "美股复权因子",
       params={"ts_code": "美股代码", **P_TRADE_DATE}),
    _a("美股数据", "美股利润表", "us_income", "美股利润表",
       params={"ts_code": "美股代码", "period_type": "FY年度/Q1-Q4季度", "end_date": "报告期", "ind_type": "准则 GAAP/IFRS"}),
    _a("美股数据", "美股现金流量表", "us_cashflow", "美股现金流量表",
       params={"ts_code": "美股代码", "period_type": "周期", "end_date": "报告期"}),
    _a("美股数据", "美股资产负债表", "us_balancesheet", "美股资产负债表",
       params={"ts_code": "美股代码", "period_type": "周期", "end_date": "报告期"}),
    _a("美股数据", "美股财务指标数据", "us_fina_indicator", "美股财务指标数据",
       params={"ts_code": "美股代码", "period_type": "周期", "end_date": "报告期"}),

    _a("宏观经济", "国内宏观", "cn_gdp", "国内生产总值（GDP）",
       params={"quarter": "季度（如 2024Q3）", "start_q": "开始季度", "end_q": "结束季度"}),
    _a("宏观经济", "国内宏观", "cn_cpi", "居民消费价格指数（CPI）",
       params={"month": "月份 YYYYMM", "start_m": "起始月", "end_m": "结束月"}),
    _a("宏观经济", "国内宏观", "cn_ppi", "工业生产者出厂价格指数（PPI）",
       params={"month": "月份", "start_m": "起始月", "end_m": "结束月"}),
    _a("宏观经济", "国内宏观", "cn_pmi", "采购经理指数（PMI）",
       params={"month": "月份", "start_m": "起始月", "end_m": "结束月"}),
    _a("宏观经济", "国内宏观", "cn_m", "货币供应量（月）",
       params={"month": "月份", "start_m": "起始月", "end_m": "结束月"}),
    _a("宏观经济", "国内宏观", "sf_month", "社融增量（月度）",
       params={"month": "月份", "start_m": "起始月", "end_m": "结束月"}),
    _a("宏观经济", "国内宏观", "shibor", "Shibor利率",
       params={"date": "日期", "start_date": "开始日期", "end_date": "结束日期"}),
    _a("宏观经济", "国内宏观", "shibor_lpr", "LPR贷款基础利率",
       params={"date": "日期", **P_START_END}),
    _a("宏观经济", "国内宏观", "shibor_quote", "Shibor报价数据",
       params={"date": "日期", **P_START_END}),
    _a("宏观经济", "国内宏观", "hibor", "Hibor利率", params={"date": "日期"}),
    _a("宏观经济", "国内宏观", "libor", "Libor利率", params={"date": "日期"}),
    _a("宏观经济", "国内宏观", "wz_index", "温州民间借贷利率",
       params={"date": "日期", "begin_date": "开始", "end_date": "结束"}),
    _a("宏观经济", "国内宏观", "gz_index", "广州民间借贷利率", params={}),
    _a("宏观经济", "国内宏观", "cn_schedule", "中国经济数据发布日程",
       params={"date": "发布日期", "begin_date": "开始", "end_date": "结束"}),
    _a("宏观经济", "国际宏观", "us_tycr", "国债收益率曲线利率",
       params={"date": "日期", "yield_curve_type": "曲线类型"}),
    _a("宏观经济", "国际宏观", "us_trycr", "国债实际收益率曲线利率", params={"date": "日期"}),
    _a("宏观经济", "国际宏观", "us_tbr", "短期国债利率", params={"date": "日期"}),
    _a("宏观经济", "国际宏观", "us_tltr", "国债长期利率", params={"date": "日期"}),
    _a("宏观经济", "国际宏观", "us_trltr", "国债长期利率平均值", params={"date": "日期"}),

    _a("大模型语料", "新闻快讯（短讯）", "news", "新闻快讯（短讯）",
       params={"src": "sina/wallstreetcn/10jqka/eastmoney/yuncaijing/fenghuang/jinrongjie/cls/yicai",
               **P_START_END},
       note="需单独权限（实测本 token 40203 时回退 AKShare）"),
    _a("大模型语料", "新闻通讯（长篇）", "major_news", "新闻通讯（长篇）",
       params={"src": "来源", **P_START_END},
       note="实测本 token 有权限但限频（40次/天、30次/小时），注意缓存"),
    _a("大模型语料", "新闻联播文字稿", "cctv_news", "新闻联播文字稿",
       params={"date": "日期 YYYYMMDD"}),
    _a("大模型语料", "券商研究报告", "research_report", "券商研究报告",
       params={"src": "来源", **P_LIMIT_OFFSET}),
    _a("大模型语料", "国家政策库", "npr", "国家政策库", params={}),
    _a("大模型语料", "央行货币政策执行报告", "monetary_policy", "央行货币政策执行报告",
       params={}),
    _a("大模型语料", "上市公司公告", "anns_d", "上市公司公告",
       params={"ts_code": P_TSCODE["ts_code"], "ann_date": "公告日期", "start_date": "开始日期", "end_date": "结束日期"}),
    _a("大模型语料", "上证e互动问答", "irm_qa_sh", "上证e互动问答",
       params={"ts_code": P_TSCODE["ts_code"], "trade_date": P_TRADE_DATE["trade_date"]}),
    _a("大模型语料", "深证易互动问答", "irm_qa_sz", "深证易互动问答",
       params={"ts_code": P_TSCODE["ts_code"], "trade_date": P_TRADE_DATE["trade_date"]}),

    _a("自选组合", "组合管理", "p_list", "组合列表", params={}),
    _a("自选组合", "组合管理", "p_get", "成分查询", params={"portfolio_name": "组合名称"}),
    _a("自选组合", "组合管理", "p_save", "组合保存", params={"portfolio_name": "组合名称"}),
    _a("自选组合", "组合删除", "p_delete", "组合删除", params={"portfolio_name": "组合名称"}),
    _a("量化因子库", "因子库", "factor_list", "因子列表", params={}),
    _a("量化因子库", "因子库", "factor_value", "因子数据",
       params={"factors": "因子代码列表", "stocks_codes": "股票列表",
               "inputs": "自定义参数", "start_date": "开始日期", "end_date": "结束日期"}),
]

def build_catalog():
    return [dict(item) for item in CATALOG]

def get_api_info(api_name):
    for item in CATALOG:
        if item["api"] == api_name:
            return dict(item)
    return None

def all_api_names():
    return sorted({item["api"] for item in CATALOG})

if __name__ == "__main__":
    from collections import Counter
    cats = Counter(i["category"] for i in CATALOG)
    print(f"共 {len(CATALOG)} 个接口条目")
    for c, n in cats.items():
        print(f"  {c}: {n}")
